# Generated by Django 4.1.2 on 2022-10-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0002_remove_user_registration_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration_model',
            name='User_Photo',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
