# Generated by Django 4.1.2 on 2022-10-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0003_alter_user_registration_model_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Home_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(upload_to='image/')),
                ('Category_Name', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
