# Generated by Django 4.1.2 on 2022-10-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0004_product_home_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_home_model',
            name='Price',
            field=models.CharField(max_length=50),
        ),
    ]
