# Generated by Django 4.1.2 on 2022-10-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0006_womens_product_home_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mens_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(upload_to='image/')),
                ('Category_Name', models.CharField(max_length=30)),
                ('Product_Name', models.CharField(max_length=100, null=True)),
                ('Price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Women_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(upload_to='image/')),
                ('Category_Name', models.CharField(max_length=30)),
                ('Product_Name', models.CharField(max_length=100, null=True)),
                ('Price', models.CharField(max_length=50)),
            ],
        ),
    ]
