# Generated by Django 4.1.2 on 2022-10-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0007_mens_product_women_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Women_Product_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(upload_to='image/')),
                ('Category_Name', models.CharField(max_length=30)),
                ('Product_Name', models.CharField(max_length=100, null=True)),
                ('Price', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Mens_Product',
            new_name='Accessories_Model',
        ),
        migrations.RenameModel(
            old_name='Women_Product',
            new_name='Mens_Product_Model',
        ),
    ]
