# Generated by Django 4.1.2 on 2022-10-30 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_lifestyle', '0008_women_product_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories_model',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mens_product_model',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='women_product_model',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Womens_Cart_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Womens_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_lifestyle.women_product_model')),
            ],
        ),
        migrations.CreateModel(
            name='Mens_Cart_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mens_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_lifestyle.mens_product_model')),
                ('User_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accessories_Cart_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accessories_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_lifestyle.accessories_model')),
                ('User_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
