# Generated by Django 4.1.2 on 2022-10-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0011_contact_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Model',
        ),
    ]
