# Generated by Django 4.1.2 on 2022-10-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0013_contact_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_model',
            name='name',
        ),
        migrations.AddField(
            model_name='contact_model',
            name='subject',
            field=models.CharField(default='qw', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact_model',
            name='email',
            field=models.EmailField(default='@gmail', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_model',
            name='message',
            field=models.CharField(default='qw', max_length=1120),
        ),
    ]
