# Generated by Django 4.1.2 on 2022-10-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0014_remove_contact_model_name_contact_model_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Model',
        ),
    ]
