# Generated by Django 4.1.2 on 2022-11-01 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_lifestyle', '0015_delete_contact_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Details_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('order_day', models.DateTimeField(auto_now_add=True)),
                ('User_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
