# Generated by Django 4.1.2 on 2022-11-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0016_order_details_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0=defual,1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=defual,1=hidden')),
                ('meta_title', models.CharField(blank=True, max_length=140)),
                ('meta_keyword', models.CharField(max_length=150)),
                ('meta_description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('product_image', models.ImageField(upload_to='image/')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('small_description', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0=defual,1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=defual,1=hidden')),
                ('meta_title', models.CharField(blank=True, max_length=140)),
                ('meta_keyword', models.CharField(max_length=150)),
                ('meta_description', models.TextField(max_length=500)),
                ('tag', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_lifestyle.categorymodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='accessories_cart_model',
            name='Accessories_Forgn',
        ),
        migrations.RemoveField(
            model_name='accessories_cart_model',
            name='User_Forgn',
        ),
        migrations.RemoveField(
            model_name='mens_cart_model',
            name='Mens_Forgn',
        ),
        migrations.RemoveField(
            model_name='mens_cart_model',
            name='User_Forgn',
        ),
        migrations.DeleteModel(
            name='Mens_Product_Home_Model',
        ),
        migrations.RemoveField(
            model_name='order_details_model',
            name='User_Forgn',
        ),
        migrations.RemoveField(
            model_name='user_registration_model',
            name='User_Forgn',
        ),
        migrations.RemoveField(
            model_name='womens_cart_model',
            name='User_Forgn',
        ),
        migrations.RemoveField(
            model_name='womens_cart_model',
            name='Womens_Forgn',
        ),
        migrations.DeleteModel(
            name='Womens_Product_Home_Model',
        ),
        migrations.DeleteModel(
            name='Accessories_Cart_Model',
        ),
        migrations.DeleteModel(
            name='Accessories_Model',
        ),
        migrations.DeleteModel(
            name='Mens_Cart_Model',
        ),
        migrations.DeleteModel(
            name='Mens_Product_Model',
        ),
        migrations.DeleteModel(
            name='Order_Details_Model',
        ),
        migrations.DeleteModel(
            name='User_Registration_Model',
        ),
        migrations.DeleteModel(
            name='Women_Product_Model',
        ),
        migrations.DeleteModel(
            name='Womens_Cart_Model',
        ),
    ]
