# Generated by Django 4.1.2 on 2022-11-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0017_categorymodel_productmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
