# Generated by Django 4.1.2 on 2022-11-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0018_alter_productmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='tag',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
