# Generated by Django 4.1.2 on 2022-11-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0019_alter_productmodel_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='Category',
            new_name='category',
        ),
    ]
