# Generated by Django 4.1.2 on 2022-11-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0020_rename_category_productmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='category',
            new_name='category_forgn',
        ),
    ]
