# Generated by Django 4.1.2 on 2022-11-15 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_lifestyle', '0021_rename_category_productmodel_category_forgn'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Registration_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Contact', models.CharField(max_length=15)),
                ('User_Address', models.CharField(max_length=100)),
                ('User_Gender', models.CharField(max_length=10)),
                ('User_Photo', models.ImageField(upload_to='image/')),
                ('User_Forgn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
