# Generated by Django 4.1.2 on 2022-11-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0023_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='product_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
