# Generated by Django 4.1.2 on 2022-11-15 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_lifestyle', '0024_alter_cartmodel_product_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('total_price', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('out for shipping', 'out for shipping'), ('completed', 'completed')], default='pending', max_length=200)),
                ('message', models.CharField(max_length=200, null=True)),
                ('tracking_no', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('User_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderitemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_lifestyle.ordermodel')),
                ('product_forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_lifestyle.productmodel')),
            ],
        ),
    ]
