# Generated by Django 4.1.2 on 2022-11-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0025_ordermodel_orderitemmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='Product_Forgn',
            new_name='product_forgn',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='User_Forgn',
            new_name='user_forgn',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='User_Forgn',
            new_name='user_forgn',
        ),
    ]
