# Generated by Django 4.1.2 on 2022-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0026_rename_product_forgn_cartmodel_product_forgn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='tag',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=defual,1=trending'),
        ),
    ]
