# Generated by Django 4.1.2 on 2022-11-17 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_lifestyle', '0029_alter_ordermodel_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='user_forgn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out for shipping', 'out for shipping'), ('completed', 'completed')], default='Out Of Delivary', max_length=200),
        ),
    ]
