# Generated by Django 4.1.2 on 2022-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_lifestyle', '0031_remove_orderitemmodel_user_forgn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='trending',
            field=models.BooleanField(default=False, help_text='1=defual,0=trending'),
        ),
    ]
